[package]
name = "temps-providers"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
temps-auth = { path = "../temps-auth" }
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }
temps-query = { path = "../temps-query" }
temps-query-postgres = { path = "../temps-query-postgres" }
temps-query-s3 = { path = "../temps-query-s3" }
temps-query-redis = { path = "../temps-query-redis" }
temps-query-mongodb = { path = "../temps-query-mongodb" }
serde = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bollard = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
sea-orm = { workspace = true }
redis = { version = "0.28.2", features = ["tokio-comp", "connection-manager"] }
mongodb = "3.3.0"
aws-sdk-s3 = { workspace = true }
aws-smithy-runtime = "1.9"
hyper-util = { version = "0.1", features = ["client", "client-legacy", "http1", "http2", "tokio"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
rand = { workspace = true }
bytes = { workspace = true }
tar = { workspace = true }
http = { workspace = true }
uuid = { workspace = true }
regex = "1.11.1"
utoipa = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
schemars = { workspace = true }
urlencoding = "2.1"

[dev-dependencies]
tokio-test = "0.4"
testcontainers = { workspace = true }
hyper = { version = "1", features = ["client", "http1", "http2"] }
