[package]
name = "temps-screenshots"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
utoipa = { workspace = true }

# Screenshot dependencies
headless_chrome = {version ="1.0.18", features = ["fetch", "offline"] }
reqwest = { workspace = true }
url = { workspace = true }
base64 = "0.21"

temps-config = { path = "../temps-config" }
temps-core = { path = "../temps-core" }

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.5"
tempfile = "3.8"
temps-database = { path = "../temps-database" }
sea-orm = { workspace = true }
