[package]
name = "temps-logs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
chrono = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
async-stream = { workspace = true }
notify = { workspace = true }
bollard = { workspace = true }
futures-util = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
# Plugin dependencies
temps-core = { path = "../temps-core" }
utoipa = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
