[package]
name = "temps-monitoring"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
serde = { workspace = true }
tokio = { workspace = true }
