[package]
name = "temps-routes"
version = "0.1.0"
edition = "2021"

[dependencies]
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }

# Database
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
sqlx = { workspace = true }

# Concurrency
parking_lot = "0.12"

# Logging
tracing = { workspace = true }
anyhow = { workspace = true }

# Async
tokio = { workspace = true }
