[package]
name = "temps-routes"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }

# Database
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
sqlx = { workspace = true }

# Concurrency
parking_lot = "0.12"

# Logging
tracing = { workspace = true }
anyhow = { workspace = true }

# Async
tokio = { workspace = true }
