[package]
name = "temps-projects"
version = "0.1.0"
edition = "2021"

[dependencies]
temps-auth = { path = "../temps-auth" }
temps-config = { path = "../temps-config" }
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }
temps-environments = { path = "../temps-environments" }
temps-git = { path = "../temps-git" }
temps-queue = { path = "../temps-queue" }
temps-providers = { path = "../temps-providers" }
temps-presets = { path = "../temps-presets" }
serde = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
sea-orm = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }
utoipa = { workspace = true }
futures = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
flate2 = { workspace = true }
http = { workspace = true }
futures-util = { workspace = true }
slug = { workspace = true }